package database.tables

import database.realtimestamp
import org.jetbrains.exposed.sql.Table

object ClientFileTable : Table(){
    val client_num = integer("Client#")
    override val primaryKey = PrimaryKey(client_num, name = "Client#")
    val ofcname = text("OfcName").nullable()
    val firstname1 = text("FirstName1").nullable()
    val lastname1 = text("LastName1").nullable()
    val firstname2 = text("FirstName2").nullable()
    val lastname2 = text("LastName2").nullable()
    val address1 = text("Address1").nullable()
    val address2 = text("Address2").nullable()
    val city = text("City").nullable()
    val state = text("State").nullable()
    val zip = text("Zip").nullable()
    val county = text("County").nullable()
    val email = text("e-Mail").nullable()
    val ophone = text("OPhone").nullable()
    val oxtension = text("OXtension").nullable()
    val ofax = text("OFax").nullable()
    val hphone = text("HPhone").nullable()
    val cellphone = text("CellPhone").nullable()
    val carphone = text("CarPhone").nullable()
    val estdate = realtimestamp("EstDate").nullable()
    val speciality = text("Speciality").nullable()
    val ofchrs = text("OfcHrs").nullable()
    val ofcmanager = text("OfcManager").nullable()
    val rateconfirm = bool("RateCnfrm?").nullable()
    val agreement = realtimestamp("Agrmt?").nullable()
    val agreement_perm = realtimestamp("AgrmtPerm").nullable()
    val pktsent = realtimestamp("PktSent?").nullable()
    val refdby = text("RefdBy").nullable()
    val preferences = text("Preferences").nullable()
    val dislikes = text("Dislikes").nullable()
    val temphyg = bool("TempHyg?").nullable()
    val daps_dollar = double("DAPS$").nullable()
    val daps_dollar_two = double("DAPS2$").nullable()
    val needs = text("Needs").nullable()
    val startdate = realtimestamp("StartDate").nullable()
    val endate = realtimestamp("EndDate").nullable()
    val days = text("Days").nullable()
    val permconf = bool("PermConf?").nullable()
    val tempconf = bool("TempConf?").nullable()
    val mlplcmnt = bool("MLPlcmnt").nullable()
    val lofaplcmnt = bool("LofAPlcmnt").nullable()
    val patnttime = text("PatntTime").nullable()
    val warndate1 = realtimestamp("WarnDate1").nullable()
    val warndate2 = realtimestamp("WarnDate2").nullable()
    val warndate3 = realtimestamp("WarnDate3").nullable()
    val cnotes = text("CNotes").nullable()
    val multioffice = text("MultiOffice?").nullable()
    val payperiods = integer("PayPeriods").nullable()
    val yeslist = bool("YesList").nullable()
    val filler = realtimestamp("Filler").nullable()
    val filler2 = double("Filler-2").nullable()
}
